### ISSUE TITLE
Request for tutorial

### ISSUE THREAD

**Issue by sri-ni** [Stickbuilt/SBGestureTableView#1]
I am new to iOS Swift working on my first app. This solves a great need of mine.

Thank you!

A step-by-step tutorial would be incredibly beneficial.

**Comment by apoorvmote** [comment]
Yes Please create step by step tutorial & your icons are no longer working.
Please update the X Code project.

**Comment by bennichols** [comment]
Ok, I also need to update the lib for Swift 1.2. I should be able to get around to it fairly soon.

**Comment by bennichols** [comment]
@firerishi @apoorvmote I believe the icon issues are fixed now and there are some instructions on how to use it. If you want to use with Swift 1.1, use the corresponding branch.
