### ISSUE TITLE
Swift 2.0 Support 

### ISSUE THREAD

**Issue by HerbstLukas** [Stickbuilt/SBGestureTableView#2]
Support for new swift 2.0 (in a second branch?) 
Would love to use this tableView!

**Comment by bennichols** [comment]
@HerbstLukas I probably won't get around to converting it until we start using Swift 2.0 ourselves. If you need it before then, I'm happy to take pull requests!

**Comment by bennichols** [comment]
I merged in a pull request under the swift2.0 branch. Please let me know if you have any issues with it.
