### ISSUE TITLE
Custom Cell with SBGestureTableView

### ISSUE THREAD

**Issue by RayanSaeed** [Stickbuilt/SBGestureTableView#3]
Can you please explain why I can't use a custom cell with this class, like by having a custom cell in a xib file or a prototype cell in the interface builder viewController??

When I add a UISwitch to the prototype cell and run the app. In the simulator it looks like this 
<img width="487" alt="screen shot 2015-08-09 at 1 14 43 pm" src="https://cloud.githubusercontent.com/assets/8598858/9154291/a1d632ba-3e98-11e5-8bba-c35472c3f22b.png">

I have tapped the first cell that's why it looks a bit different. Can you please explain what am i doing wrong here?

**Comment by bennichols** [comment]
I wouldn't be able to tell you without seeing code. I use this with custom SBGestureTableViewCell subclasses all the time!

**Comment by RayanSaeed** [comment]
@bennichols Just for the sake of anyone in future... This issue was solved by making the label's background colour = UIColor.clearColor and then everything was visible again..
